#!/bin/bash

COMMIT_MESSAGE_PATTERN='^Issue #[0-9]+: .+'

while read oldrev newrev refname; do
    for commit in $(git rev-list $oldrev..$newrev); do
        commit_message=$(git log --format=%B -n 1 $commit)
        if [[ ! $commit_message =~ $COMMIT_MESSAGE_PATTERN ]]; then
            echo "Invalid commit message format detected."
            echo "Commit: $commit"
            echo "Message: $commit_message"
            exit 1
        fi
    done
done

exit 0